org.gradle.jvmargs=-Xmx3072M -XX:MaxMetaspaceSize=512M -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false
systemProp.org.gradle.internal.http.connectionTimeout=30000
systemProp.org.gradle.internal.http.socketTimeout=60000
kotlin.daemon.jvm.args=-Xmx512M
